# Generated by Django 3.1.7 on 2021-06-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nationality',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relaxation_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_relaxation_rules', to='user.relaxationmaster'),
        ),
    ]
