# Generated by Django 3.1.7 on 2021-06-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210605_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_fresher',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
