# Generated by Django 3.1.7 on 2021-06-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210615_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthentication',
            name='is_first_login',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='reset_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='reset_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='sms_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
