# Generated by Django 3.1.7 on 2021-06-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210617_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthentication',
            name='is_locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='is_suspended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
