# Generated by Django 3.1.7 on 2021-05-29 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_posting', '0001_initial'),
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobpositions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temporarypositionmaster',
            name='temp_position_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_positon', to='job_posting.newpositionmaster'),
        ),
        migrations.AddField(
            model_name='selectionprocesscontent',
            name='selection_committee',
            field=models.ManyToManyField(blank=True, related_name='selection_committee', to='job_posting.SelectionCommitteeMaster'),
        ),
        migrations.AddField(
            model_name='positionqualificationmapping',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postion', to='job_posting.newpositionmaster'),
        ),
        migrations.AddField(
            model_name='positionqualificationmapping',
            name='qualification',
            field=models.ManyToManyField(blank=True, related_name='qualification_name', to='job_posting.QualificationMaster'),
        ),
        migrations.AddField(
            model_name='permanentpositionmaster',
            name='perm_position_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_positon', to='job_posting.newpositionmaster'),
        ),
        migrations.AddField(
            model_name='newpositionmaster',
            name='documents_required',
            field=models.ManyToManyField(blank=True, related_name='position_master_required_documents', to='document.NewDocumentMaster'),
        ),
        migrations.AddField(
            model_name='newpositionmaster',
            name='information_required',
            field=models.ManyToManyField(blank=True, related_name='required_info', to='document.InformationMaster'),
        ),
        migrations.AddField(
            model_name='newpositionmaster',
            name='qualification',
            field=models.ManyToManyField(blank=True, related_name='qualification_master_position', to='job_posting.QualificationMaster'),
        ),
        migrations.AddField(
            model_name='newpositionmaster',
            name='qualification_job_history',
            field=models.ManyToManyField(blank=True, related_name='qualification_job_history', to='job_posting.QualificationJobHistoryMaster'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postion', to='job_posting.newpositionmaster'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='qualification',
            field=models.ManyToManyField(blank=True, related_name='job_qualification', to='job_posting.QualificationMaster'),
        ),
        migrations.AddField(
            model_name='jobpostingrequirementpositions',
            name='job_posting_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_position', to='job_posting.jobpostingrequirement'),
        ),
        migrations.AddField(
            model_name='jobpostingrequirementpositions',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_position', to='job_posting.temporarypositionmaster'),
        ),
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='division_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posting_requirement_division', to='job_posting.division'),
        ),
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='manpower_positions',
            field=models.ManyToManyField(blank=True, related_name='job_positions', through='job_posting.JobPostingRequirementPositions', to='job_posting.TemporaryPositionMaster'),
        ),
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='zonal_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posting_requirement_zonal_lab', to='job_posting.zonallab'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posting_department', to='job_posting.department'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division', to='job_posting.division'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='documents_required',
            field=models.ManyToManyField(blank=True, related_name='required_documents', to='document.NewDocumentMaster'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='documents_uploaded',
            field=models.ManyToManyField(blank=True, null=True, related_name='documents', to='job_posting.JobDocuments'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='manpower_positions',
            field=models.ManyToManyField(blank=True, related_name='job_positions', to='job_posting.PositionQualificationMapping'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='office_memorandum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_memo', to='job_posting.jobdocuments'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='project_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posting_project_number', to='job_posting.jobpostingrequirement'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='zonal_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonal_lab', to='job_posting.zonallab'),
        ),
    ]
