# Generated by Django 3.1.7 on 2021-05-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_auto_20210529_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceconditions',
            old_name='descriprtion',
            new_name='description',
        ),
    ]
