# Generated by Django 3.1.7 on 2021-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_auto_20210529_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpositionmaster',
            name='qualification_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
