# Generated by Django 3.1.7 on 2021-06-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0005_auto_20210605_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='department',
        ),
    ]
