# Generated by Django 3.1.7 on 2021-06-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0008_auto_20210612_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobpositions',
            name='job_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posting_applicants', to='job_posting.jobposting'),
        ),
    ]
