# Generated by Django 3.1.7 on 2021-06-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0009_auto_20210612_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjobpositions',
            name='appealed',
        ),
        migrations.AddField(
            model_name='userjobpositions',
            name='appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal', to='job_posting.appealmaster'),
        ),
        migrations.AlterField(
            model_name='userjobpositions',
            name='applied_job_status',
            field=models.CharField(blank=True, choices=[('received', 'RECEIVED'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED'), ('shortlisted', 'SHORTLISTED'), ('offered', 'OFFERED'), ('hired', 'HIRED'), ('interview', 'INTERVIEW'), ('awaiting review', 'AWAITING_REVIEW'), ('closed', 'CLOSED'), ('appealed', 'APPEALED')], max_length=50, null=True),
        ),
    ]
