# Generated by Django 3.1.7 on 2021-06-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_subscription'),
        ('job_posting', '0011_auto_20210628_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField()),
                ('category', models.CharField(choices=[('Contract_Basis', 'contract_basis'), ('Permanent', 'permanent')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='userjobpositions',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='application_documents', to='user.UserDocuments'),
        ),
        migrations.AlterField(
            model_name='userjobpositions',
            name='applied_job_status',
            field=models.CharField(blank=True, choices=[('document pending', 'DOCUMENT_PENDING'), ('received', 'RECEIVED'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED'), ('shortlisted', 'SHORTLISTED'), ('offered', 'OFFERED'), ('hired', 'HIRED'), ('interview', 'INTERVIEW'), ('awaiting review', 'AWAITING_REVIEW'), ('closed', 'CLOSED'), ('appealed', 'APPEALED')], max_length=50, null=True),
        ),
    ]
